---
language: python
python: 2.7

sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
